var cfg = {}

cfg.language = 'fr'

cfg.mainColor = 'rgb(81, 148, 40)'

cfg.Translation = {
    ['fr']: {
        //HTML
        email: "Email",
        password: "Mots de passe",
        passwordrepeat: "Répéter le mot de passe",
        buttonLogIn: "Connexion",
        buttonRegister: "S'inscrire",
        toRegisterText: "Pas encore de compte?",
        toRegisterButton: "S'inscrire maintenant",
        toLogInText: "Vous avez déjà créé un compte?",
        toLogInButton: "Connexion",
        info: "Connecté en tant que:",
        logout: "Se déconnecter",
        inbox_text: "Boîte de réception",
        outbox_text: "Boîte d'envoi",
        sendmail: "Envoyer un mail",
        prefixSubject: "Sujet: ",
        prefixMessage: "Message:",
        fromToPrefixTo: "Destinataire: ",
        fromToPrefixFrom: "Expéditeur: ",
        receiverEmail: "Destinataire...",
        subjectEmail: "Sujet...",
        refresh: 'rafraîchir',
        //JS
        errorCode1: "E-mail ou mot de passe incorrect",
        errorCode2: "L'email existe déjà",
        errorCode3: "Merci de remplir tous les champs!",
        errorCode4: "Ne peut pas avoir @ dans l'e-mail!",
        registerSuccess: "Inscription complète!",
        registerSuccess_desc: "Inscription terminée! Vous êtes sur le point d'être connecté",
        registerFailed: "Inscription annulée!",
        registerFailed_desc: "L'email existe déjà!",
        LoginFailed: "Connexion interrompue!",
        LoginFailed_desc: "L'e-mail ou le mot de passe n'est pas correct!",
        mailsent: "Email envoyé",
        mailsent_desc1: "Votre e-mail a bien été envoyé à ",
        mailsent_desc2: "!",
        mailfailed: "Erreur",
        mailfailed_desc1: "L'adresse mail ",
        mailfailed_desc2: " n'a pas été trouvé!",
        
    },

    ['de']: {
        //HTML
        email: "E-Mail Adresse",
        password: "Passwort",
        passwordrepeat: "Passwort wiederholen",
        buttonLogIn: "Anmelden",
        buttonRegister: "Registrieren",
        toRegisterText: "Noch kein Account?",
        toRegisterButton: "Zur Regestrierung",
        toLogInText: "Bereits ein Account erstellt?",
        toLogInButton: "Zur Anmeldung",
        info: "Eingeloggt als:",
        logout: "Ausloggen",
        inbox_text: "Posteingang",
        outbox_text: "Postausgang",
        sendmail: "Nachricht senden",
        prefixSubject: "Betreff: ",
        prefixMessage: "Nachricht:",
        fromToPrefixTo: "Empfänger: ",
        fromToPrefixFrom: "Sender: ",
        refresh: 'aktualisieren',
        //JS
        errorCode1: "Falsche Login-Daten",
        errorCode2: "E-Mail existiert bereits",
        errorCode3: "Bitte fülle alle Felder aus!",
        errorCode4: "Zu viele @ in der E-Mail adresse!",
        registerSuccess: "Registrierung erfolgreich!",
        registerSuccess_desc: "Die Regestrierung war erfolgreich und du wurdest eingelogt!",
        registerFailed: "Registrierung fehlgeschlagen!",
        registerFailed_desc: "Die E-Mail Adresse existiert bereits!",
        LoginFailed: "LogIn fehlgeschlagen!",
        LoginFailed_desc: "Die E-Mail Adresse und Passwort stimmen nicht überein!",
        mailsent: "E-Mail gesendet",
        mailsent_desc1: "Deine E-Mail wurder erfolgreich an ",
        mailsent_desc2: " gesendet!",
        mailfailed: "Fehler",
        mailfailed_desc1: "Die E-Mail Adresse ",
        mailfailed_desc2: " wurde nicht gefunden!",
    },

    ['en']: {
        //HTML
        email: "E-mail",
        password: "password",
        passwordrepeat: "password repeat",
        buttonLogIn: "Login",
        buttonRegister: "Register",
        toRegisterText: "No account yet?",
        toRegisterButton: "Register now",
        toLogInText: "Already created an account?",
        toLogInButton: "Login",
        info: "Logged in as:",
        logout: "Logout",
        inbox_text: "Inbox",
        outbox_text: "Outbox",
        sendmail: "Send mail",
        prefixSubject: "Subject: ",
        prefixMessage: "Message:",
        fromToPrefixTo: "Receiver: ",
        fromToPrefixFrom: "Sender: ",
        receiverEmail: "Receiver...",
        subjectEmail: "Subject...",
        refresh: 'refresh',
        //JS
        errorCode1: "Wrong E-Mail or password",
        errorCode2: "E-Mail already exists",
        errorCode3: "Please fill in all fields!",
        errorCode4: "To many @ in the email!",
        registerSuccess: "Registration complete!",
        registerSuccess_desc: "Registration completed! You are about to be logged in",
        registerFailed: "Registration aborted!",
        registerFailed_desc: "E-Mail already exists!",
        LoginFailed: "Login aborted!",
        LoginFailed_desc: "E-Mail or password is not correct!",
        mailsent: "E-Mail sent",
        mailsent_desc1: "Your mail was successfully sent to ",
        mailsent_desc2: "!",
        mailfailed: "Error",
        mailfailed_desc1: "The mail adress ",
        mailfailed_desc2: " was not found!",
        
    }
}